version: '3.8'

services:
  main-ctlr:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    cap_add:
    - NET_ADMIN # for Tailscale
    depends_on:
    - yaw-ctlr
    - anemometer
    - blade-1
    - blade-2
    - blade-3
    volumes:
    - /lib/modules:/lib/modules:ro # for Tailscale
    - /dev/net/tun:/dev/net/tun    # for Tailscale
    - ./configs/ot-sim/main-controller.xml:/etc/ot-sim/config.xml
    - ./configs/ot-sim/node-red.json:/etc/node-red.json
    ports:
    - 1880:1880
    environment:
    - OTSIM_TAILSCALE_AUTHKEY=${OTSIM_TAILSCALE_AUTHKEY} # for Tailscale
    hostname: ${HOSTNAME} # for Tailscale
  yaw-ctlr:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    volumes:
    - ./configs/ot-sim/yaw-controller.xml:/etc/ot-sim/config.xml
  anemometer:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    volumes:
    - ./configs/ot-sim/anemometer.xml:/etc/ot-sim/config.xml
    - ./configs/ot-sim/weather.csv:/etc/ot-sim/data/weather.csv
  blade-1:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    volumes:
    - ./configs/ot-sim/blade-1.xml:/etc/ot-sim/config.xml
  blade-2:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    volumes:
    - ./configs/ot-sim/blade-2.xml:/etc/ot-sim/config.xml
  blade-3:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    volumes:
    - ./configs/ot-sim/blade-3.xml:/etc/ot-sim/config.xml
